export const SITE = {
  name: "Shedli Auto",
  legalName: "SHEDLI AUTO",
  legalForm: "SASU au capital de 100 €",
  url: "https://shedliauto.com",
  phone: "06 28 43 88 44",
  phoneHref: "tel:+33628438844",
  phoneInternational: "+33 6 28 43 88 44",
  whatsapp: "https://wa.me/33628438844",
  email: "shedliauto@gmail.com",
  address: {
    street: "24 rue des Ebisoires",
    city: "Plaisir",
    zip: "78370",
    region: "Île-de-France",
    country: "France",
    full: "24 rue des Ebisoires, 78370 Plaisir",
  },
  siren: "933 679 482",
  siret: "933 679 482 00010",
  tva: "FR13933679482",
  rcs: "Versailles",
  ape: "4520A",
  manager: "Saif-Dine Baccouche",
  managerRole: "Président",
  hours: {
    weekdays: "Lun – Ven : 8h – 19h",
    saturday: "Sam : 9h – 17h",
    sunday: "Dim : Fermé",
  },
  zone: {
    label: "Yvelines & Île-de-France",
    department: "78",
    cities: [
      "Plaisir",
      "Versailles",
      "Saint-Germain-en-Laye",
      "Poissy",
      "Sartrouville",
      "Chatou",
      "Le Vésinet",
      "Maisons-Laffitte",
      "Conflans-Sainte-Honorine",
      "Les Mureaux",
      "Mantes-la-Jolie",
      "Trappes",
      "Montigny-le-Bretonneux",
      "Guyancourt",
      "Élancourt",
      "Maurepas",
      "Rambouillet",
      "Bois-d'Arcy",
      "Fontenay-le-Fleury",
      "Villepreux",
      "Nanterre",
      "Boulogne-Billancourt",
      "Argenteuil",
      "Cergy",
      "Saint-Denis",
      "Créteil",
      "Évry-Courcouronnes",
    ],
  },
  social: {
    instagram: "https://instagram.com/shedli_auto",
  },
} as const;
